{% set name = "inspyred" %}
{% set version = "1.0.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: acc1215003a8937ef174f2719e8256bf21b4bb67a9aa7de495db6044f4055961

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - python >=3.6

test:
  imports:
    - inspyred

about:
  home: http://aarongarrett.github.io/inspyred/
  license: MIT
  license_file: LICENSE
  summary: A framework for creating bio-inspired computational intelligence algorithms

extra:
  recipe-maintainers:
    - jschueller
