travis:
  secure:
    BINSTAR_TOKEN: n2p8/mRG9iSP/bTeHQBkjobY3VeupAYKIQZTMZJC9Wl+nrlxXRNxVD1WDoKLCOWZayGFByJ1jK6savuXSc98ba8/fAMLicboFkfcgiKgqYeN3XeKI/xyWViGsj7ErhO0EtbVe8Lc6jBS57jgTkX6YDrvPIdB0j196DcV1DeLaYQCIopj260tgKKXMMwmSwD7CLQH35Q44h6BA+n3w26W/tJASG/PIFHXcugSiCMMp9sH7oZYh/6sJq8ZW3c35QKahFtEq4D/alZEH5cUgcyH2Dw6wn+2NDwlB6+R3OIHiOOG/Qvr5ju8YUZFu4y2qDiCwey/r1THFAZDg3lUxr7FNSYo/5WPqg3UpYEOx7PFxPq8B6hTJGfEha/02uaapBNqoyRALR2EV2Rh4sRCOYoRnuBVMM1t6ONx81mw7WwrofiLeSVWfuWwYwqQv0LEyGsQzwD2AZspaw0tSHKUsc/jNN62ayCdalNO75ayrZ+SQrqBa0S2fdg9I3fEZE/B23uxrOMGg05doUV4s1jode53xTBB59qbS1/T32CUJUeWVkMXBK71xQjGGxWWw8di2Lm3SvGyhqG90oWhkYlzW1rchIrKpYdM8OZA9bW7bo1oERnNo2f+zBTjQrx/hgJmJt8d9uaw5wUivdc3IGQaKtaTrNG72f5ZuhgoJlbMJLvsdxE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
