appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Glg4ObGp7KYfzKR+gCwDsQWd7O97pYoP5ZIRZEWwS+hDm7xZ0pcqSdz6tnV2JMMJKSmnTVfXEUBsd3vIiZ8p1+qugdaLCxutkijn8CJC1BrBq4UHffVrP+cHfc+HcUe+9bBAqYxetXxEh+wuHBPmacWqNYJalk64h8Y93a71ql4Ev6swHj1LwZc2ZV1X9kxNvvYugCfFuPtAvP+OkxXsoT8vHQCo22elswjGR2xipd3Un1kkwU6daORcuIg3ReF2uCe8Do18OQ1cpedazsFuujvRVPWL7ty9HJ6+S6H0X8IFuTKUGGfvDEkhVy5yMmLfHvUAPP/8lMoWvBr5cFs3hWPX0Xg49scAo4/bAz0fnMQQpK7fqSVolLb2H9S7kCuvzzxirXKqvzmyal8LjlD8KBpiIzoAq/jN6WCk7nIu7VkdYFbQRnChzzR+tc11cyOk5WtzYjDwQCNzK49vYgljxbx57xbIEWdcwfnu785w43AFO+21FTJpXyZ1QhoBE6UfTQABLxTY9XXMqWUkgEMRQwqmUjUgEJx2dKyYObigkLxZAOU47iHEv509FCpA11dCgF/qnPUjDcjC7y6bfLf7D1a4jTdqEw6f1yz8Sb7e0hfFe88MpmTAcYxcjiHPhfREzIHMIuLoVyDWo53XbynZYogpSVPsGPlqohKRNa0qvfs=}
